export interface Equation {
  id: number;
  label: string;
  formula: string;
}

export const equations: Equation[] = [
  { id: 1, label: "z² + c", formula: "z² + c" },
  { id: 2, label: "z³ + c", formula: "z³ + c" },
  { id: 3, label: "z⁴ + c", formula: "z⁴ + c" },
  { id: 4, label: "z⁵ + c", formula: "z⁵ + c" },
  { id: 5, label: "(z²+c)/(z-c)", formula: "(z² + c) / (z - c)" },
  { id: 6, label: "z² - z - c", formula: "z² - (z + c)" },
  { id: 7, label: "z³-z²+z+c", formula: "z³ - z² + z + c" },
  { id: 8, label: "(1+c)z-cz²", formula: "(1+c)z - cz²" },
  { id: 9, label: "z³/(1+cz²)", formula: "z³ / (1 + cz²)" },
  { id: 10, label: "(z-1)(z+½)(z²-1)+c", formula: "(z-1)(z+0.5)(z²-1) + c" },
  { id: 11, label: "(z²+1+c)/(z²-1-c)", formula: "(z²+1+c) / (z²-1-c)" },
  { id: 12, label: "z^1.5 + c", formula: "z^1.5 + c" },
  { id: 13, label: "exp(z) - c", formula: "exp(z) - c" },
  { id: 14, label: "z³-0.5+c·exp(-z)", formula: "z³ - 0.5 + c·exp(-z)" },
  { id: 15, label: "cz-1+c·exp(-z)", formula: "cz - 1 + c·exp(-z)" },
  { id: 16, label: "(4z⁵+c)/(5z⁴)", formula: "(4z⁵ + c) / (5z⁴)" },
  { id: 17, label: "z⁵-z³+z+c", formula: "z⁵ - z³ + z + c" },
  { id: 18, label: "z³ + z + c", formula: "z³ + z + c" },
  { id: 19, label: "2z·sin(Re)+cz·cos(Im)+c", formula: "2z·sin(Re(z)) + cz·cos(Im(z)) + c" },
  { id: 20, label: "z·exp(-z) + c", formula: "z·exp(-z) + c" },
  { id: 21, label: "c·exp(-z) + z²", formula: "c·exp(-z) + z²" },
  { id: 22, label: "(z²+c)² + z + c", formula: "(z²+c)² + z + c" },
  { id: 23, label: "(z+sin(z))² + c", formula: "(z + sin(z))² + c" },
  { id: 24, label: "z² + c³", formula: "z² + c³" },
  { id: 25, label: "(z²+c)/(z²-1-c)", formula: "(z²+c) / (z²-1-c)" },
  { id: 26, label: "z²cos(Im)+cz·sin(Re)+c", formula: "z²·cos(Im(z)) + cz·sin(Re(z)) + c" },
  { id: 27, label: "z²cos(Re)+cz·sin(Im)+c", formula: "z²·cos(Re(z)) + cz·sin(Im(z)) + c" },
  { id: 28, label: "z²cos(|z|)+cz·sin(|z|)+c", formula: "z²·cos(|z|) + cz·sin(|z|) + c" },
  { id: 29, label: "sin(z²)·tan(z²)+c", formula: "sin(z²)·tan(z²) + c" },
  { id: 30, label: "cz² + zc²", formula: "cz² + zc²" },
  { id: 31, label: "exp(sin(cz))", formula: "exp(sin(cz))" },
  { id: 32, label: "c(sin(z)+cos(z))", formula: "c·(sin(z) + cos(z))" },
  { id: 33, label: "(z²+c)²/(z-c)", formula: "(z²+c)² / (z-c)" },
  { id: 34, label: "c(sin+cos)(z³+z+c)", formula: "c·(sin(z)+cos(z))·(z³+z+c)" },
  { id: 35, label: "c·exp(z)·cos(cz)", formula: "c·exp(z)·cos(cz)" },
  { id: 36, label: "(z³+z+c)c(sin+cos)", formula: "(z³+z+c)·c·(sin(z)+cos(z))" },
  { id: 37, label: "1-z²+z⁴/(2+4z)+c", formula: "1 - z² + z⁴/(2+4z) + c" },
  { id: 38, label: "z² + z^1.5 + c", formula: "z² + z^1.5 + c" },
  { id: 39, label: "1-z²+z⁵/(2+4z)+c", formula: "1 - z² + z⁵/(2+4z) + c" },
  { id: 40, label: "z³·exp(z) + c", formula: "z³·exp(z) + c" },
  { id: 41, label: "(z+sin)²+c·e^-z+z²+c", formula: "(z+sin(z))² + c·exp(-z) + z² + c" },
  { id: 42, label: "z³/(1+cz²)+exp(z)-c", formula: "z³/(1+cz²) + exp(z) - c" },
  { id: 43, label: "(z+sin(z))²+c·exp(z)+c", formula: "(z+sin(z))² + c·exp(z) + c" },
  { id: 44, label: "(z³+c)/z²", formula: "(z³+c) / z²" },
  { id: 45, label: "(z³+c)/z", formula: "(z³+c) / z" },
  { id: 46, label: "(z-√z)² + c", formula: "(z - √z)² + c" },
  { id: 47, label: "(z+c)² + (z+c)", formula: "(z+c)² + (z+c)" },
  { id: 48, label: "(z+c)³ - (z+c)²", formula: "(z+c)³ - (z+c)²" },
  { id: 49, label: "(z³-z²)² + c", formula: "(z³-z²)² + c" },
  { id: 50, label: "(z²-z)² + c", formula: "(z²-z)² + c" },
  { id: 51, label: "(z-√z)² + c", formula: "(z - √z)² + c" },
  { id: 52, label: "(z²+√z)² + c", formula: "(z² + √z)² + c" },
  { id: 53, label: "z²·e^z - z·e^z + c", formula: "z²·exp(z) - z·exp(z) + c" },
  { id: 54, label: "(exp(cz)+c)²", formula: "(exp(cz) + c)²" },
  { id: 55, label: "z⁵ + cz³ + c", formula: "z⁵ + cz³ + c" },
  { id: 56, label: "exp(z²+c)", formula: "exp(z² + c)" },
  { id: 57, label: "z⁸ + c", formula: "z⁸ + c" },
];

export function getEquation(id: number): Equation | undefined {
  return equations.find(eq => eq.id === id);
}
